FROM quay.io/keycloak/keycloak:26.0.0

HEALTHCHECK --interval=30s --timeout=3s --start-period=60s --retries=3 \
  CMD curl -f http://localhost:8080/health || exit 1

COPY ./bank-theme /opt/keycloak/themes/bank-theme

ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start", "--proxy-headers", "xforwarded", "--hostname-strict=false", "--http-enabled=true"]